-- MySQL Script generated by MySQL Workbench
-- Tue Jun 18 03:27:05 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema menu_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema menu_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `menu_db` DEFAULT CHARACTER SET utf8mb3 ;
-- -----------------------------------------------------
-- Schema menu_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema menu_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `menu_db` DEFAULT CHARACTER SET utf8mb3 ;
USE `menu_db` ;

-- -----------------------------------------------------
-- Table `menu_db`.`loginAdm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menu_db`.`loginAdm` (
  `id` INT NOT NULL,
  `matricula` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

USE `menu_db` ;

-- -----------------------------------------------------
-- Table `menu_db`.`mesas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menu_db`.`mesas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numMesa` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `menu_db`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menu_db`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(11) NOT NULL,
  `mesas_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cliente_mesas1_idx` (`mesas_id` ) ,
  CONSTRAINT `fk_cliente_mesas1`
    FOREIGN KEY (`mesas_id`)
    REFERENCES `menu_db`.`mesas` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `menu_db`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menu_db`.`funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `dataNasc` DATE NULL DEFAULT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `tel` VARCHAR(10) NOT NULL,
  `matricula` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NULL,
  `loginAdm_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_funcionario_loginAdm1_idx` (`loginAdm_id` ) ,
  CONSTRAINT `fk_funcionario_loginAdm1`
    FOREIGN KEY (`loginAdm_id`)
    REFERENCES `menu_db`.`loginAdm` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `menu_db`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menu_db`.`item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  `arqImg` VARCHAR(128) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `menu_db`.`pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menu_db`.`pagamentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipoPag` VARCHAR(45) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `cliente_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pagamentos_cliente1_idx` (`cliente_id` ) ,
  CONSTRAINT `fk_pagamentos_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `menu_db`.`cliente` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `menu_db`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menu_db`.`pedidos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `funcionario_id` INT NULL DEFAULT NULL,
  `mesas_id` INT NULL,
  INDEX `fk_pedidos_funcionario_idx` (`funcionario_id` ) ,
  PRIMARY KEY (`id`),
  INDEX `fk_pedidos_mesas1_idx` (`mesas_id` ) ,
  CONSTRAINT `fk_pedidos_funcionario`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `menu_db`.`funcionario` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pedidos_mesas1`
    FOREIGN KEY (`mesas_id`)
    REFERENCES `menu_db`.`mesas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `menu_db`.`pedidos_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menu_db`.`pedidos_item` (
  `item_id` INT NULL,
  `pedidos_id` INT NULL,
  `qtd` INT NULL,
  `valor` DOUBLE NULL,
  `nome` VARCHAR(45) NULL,
  `arqImg` VARCHAR(128) NULL,
  `total` DOUBLE NULL,
  INDEX `fk_item_has_pedidos_pedidos1_idx` (`pedidos_id` ) ,
  INDEX `fk_item_has_pedidos_item1_idx` (`item_id` ) ,
  CONSTRAINT `fk_item_has_pedidos_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `menu_db`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_has_pedidos_pedidos1`
    FOREIGN KEY (`pedidos_id`)
    REFERENCES `menu_db`.`pedidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
